### ISSUE TITLE
Preprocess the RigNet dataset

### ISSUE THREAD

**Issue by Kebii** [zycliao/skeleton-free-pose-transfer#12]
Hi, thanks for your excellent work!
I have download the "ModelResource_RigNetv1_preproccessed" data and use the "data_proc/rignet_preproc.py" script to preprocess it. But most of the .obj files were fail-processed.

Traceback (most recent call last):
  File "/code/skeleton-free-pose-transfer/data_proc/rignet_preproc.py", line 196, in <module>
    tpl_edge_index = get_tpl_edges(m.v, m.f)
  File "/code/skeleton-free-pose-transfer/utils/geometry.py", line 133, in get_tpl_edges
    neighbor_ids = np.concatenate(neighbor_ids, axis=0)
  File "<__array_function__ internals>", line 180, in concatenate
ValueError: need at least one array to concatenate

How can I fix this problem?

**Comment by Kebii** [comment]
I found the cause of the error.

o3d_wrapper.py, line 25 should be written as:
`onef = np.array([int(k.split("//")[0]) for k in line.split(' ')[1:]])`
to load RigNet mesh.
